spring.application.name=ShutterStore

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=shutterstore;encrypt=false
spring.datasource.username=sa
spring.datasource.password=1234
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect


jwt.secret=MySuperSecretKeyForShutterStoreJwtAuthentication2026VeryLongKey